name: McftChat
main: im.mcft.mcftchat.McftChat
version: 1.3.7
author: laCour
description: >
             Allows you to send messages to channels
commands:
  mcftchat:
    description: Sends a message to a channel
    usage: /<command> <ch> <message>  -OR-  /<ch> <message>