name: McftChat
main: com.mcftmedia.bukkit.mcftchat.McftChat
version: 1.2
website: http://world-of-minecraft.com
author: laCour
description: >
             Allows you to send messages to channels
commands:
  mcftchat:
    description: Sends a message to a channel
    usage: /<command> <ch> <message>  -OR-  /<ch> <message>